apiVersion: v1
kind: Secret
metadata:
  name: cnn-classifier-secrets
  namespace: cnn-classifier
type: Opaque
stringData:
  # MLflow tracking server — runs inside Minikube as a ClusterIP service
  MLFLOW_TRACKING_URI: "http://mlflow-server:5000"
