AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False  # Remove VGG16 classification head
EPOCHS: 10
CLASSES: 2 # Normal, Tumor
WEIGHTS: imagenet
LEARNING_RATE: 0.01
